**Icha Meisya Kurnia (25031554047)**

**Putri Najwa Zuleyka Al Hasni (25031554076)**

#**SCRAPE USING HTTP**

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import re

url = 'https://news.detik.com/berita/d-8647946/bpbd-karhutla-di-kalimantan-selatan-capai-12-ribu-hektare'
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36'
}
response = requests.get(url, headers=headers)
soup = BeautifulSoup(response.text, 'html.parser')
paragraph_num = []
isi_inti_list = []
article_body = soup.find('div', class_='detail__body-text')
iklan_patterns = [
    r'SCROLL TO CONTINUE WITH CONTENT',
    r'ADVERTISEMENT',
    r'Baca juga:.*',
    r'Simak juga Video.*',
    r'\[Gambas:.*\]'
]

if article_body:
    paragraphs = article_body.find_all('p')
    idx = 1
    for p in paragraphs:
        text = p.text.strip()
        for pattern in iklan_patterns:
            text = re.sub(pattern, '', text, flags=re.IGNORECASE).strip()
        text = re.sub(r'^Jakarta\s*-\s*', '', text)
        if text and not p.find('a'):
            paragraph_num.append(f"Paragraf {idx}")
            isi_inti_list.append(text)
            idx += 1

df = pd.DataFrame({
    'Bagian': paragraph_num,
    'Inti Paragraf': isi_inti_list
})

df

       Bagian                                      Inti Paragraf
0  Paragraf 1  Dilansir Antara, Jumat (4/9/2026), Kepala BPBD...
1  Paragraf 2  Berdasarkan sebaran kejadian, Kota Banjarbaru ...
2  Paragraf 3  Kabupaten Tanah Laut mencatat 359 kejadian den...
3  Paragraf 4  Selanjutnya, Barito Kuala 168 kejadian dengan ...
4  Paragraf 5  Sementara itu, Hulu Sungai Tengah 58 kejadian ...
5  Paragraf 6  Selain kejadian karhutla hingga periode yang s...
6  Paragraf 7  BPBD Kalsel menegaskan pemantauan titik panas ...
7  Paragraf 8  "Pengendalian karhutla membutuhkan sinergi sel...

# **SCRAPE USING API**

In [ ]:
url = "https://api.spaceflightnewsapi.net/v4/articles/"
page = requests.get(url)
data = page.json()

In [ ]:
articles = data["results"]
articles

[{'id': 40077,
  'title': 'European Lunar Rover Secures Spot Aboard Blue Origin Blue Moon Mission',
  'authors': [{'name': 'European Spaceflight', 'socials': None}],
  'url': 'https://europeanspaceflight.com/european-lunar-rover-secures-spot-aboard-blue-origin-blue-moon-mission/',
  'image_url': 'https://europeanspaceflight.com/wp-content/uploads/2026/09/European-Lunar-Rover-Secures-Spot-Aboard-Blue-Origin-Blue-Moon-Mission.webp',
  'news_site': 'European Spaceflight',
  'summary': 'Belgium’s Space Applications Services has secured a ride for its LUVMI-M rover aboard a Blue Origin Blue Moon Mark 1 lunar lander. The company announced the agreement on 23 September, saying the mission is on track to become Europe’s first fully commercial lunar rover mission. Although development of the LUVMI family has benefited from public […]\nThe post European Lunar Rover Secures Spot Aboard Blue Origin Blue Moon Mission appeared first on European Spaceflight.',
  'published_at': '2026-09-24T13:45:53Z',
  'updated_at': '2026-09-24T13:50:09.677538Z',
  'featured': False,
  'launches': [],
  'events': []},
 {'id': 40074,
  'title': 'Starfish Space’s first Otter servicing vehicle slated for Transporter-18',
  'authors': [{'name': 'Chris Bergin', 'socials': None}],
  'url': 'https://www.nasaspaceflight.com/2026/09/starfish-spaces-otter-transporter-18/',
  'image_url': 'https://www.nasaspaceflight.com/wp-content/uploads/2026/09/NSF-2026-09-24-04-20-42-246.jpg',
  'news_site': 'NASASpaceflight',
  'summary': 'Starfish Space has confirmed that its first full-scale Otter satellite servicing vehicle is complete and…\nThe post Starfish Space’s first Otter servicing vehicle slated for Transporter-18 appeared first on NASASpaceFlight.com.',
  'published_at': '2026-09-24T13:00:13Z',
  'updated_at': '2026-09-24T13:00:23.413519Z',
  'featured': False,
  'launches': [],
  'events': []},
 {'id': 40075,
  'title': 'New tests for rendezvous and docking interoperability',
  'authors': [{'name': 'ESA', 'socials': None}],
  'url': 'https://www.esa.int/Enabling_Support/Space_Engineering_Technology/New_tests_for_rendezvous_and_docking_interoperability',
  'image_url': 'https://www.esa.int/var/esa/storage/images/esa_multimedia/images/2026/09/rendezvous_tests_in_esa_s_robotics_lab/27537873-1-eng-GB/Rendezvous_tests_in_ESA_s_robotics_lab_card_full.gif',
  'news_site': 'ESA',
  'summary': 'Currently, space missions are one-shot affairs: satellites are sent to orbit to do their mission until they run out of fuel. The European Space Agency is working on a more sustainable future where satellites and spacecraft can rendezvous, dock, refuel, repair, recalibrate and even be repurposed for new missions indefinitely.\xa0',
  'published_at': '2026-09-24T13:00:00Z',
  'updated_at': '2026-09-24T13:20:20.214928Z',
  'featured': False,
  'launches': [],
  'events': []},
 {'id': 40076,
  'title': 'Win a trip to ESA to witness BepiColombo arrive at Mercury',
  'authors': [{'name': 'ESA', 'socials': None}],
  'url': 'https://www.esa.int/Science_Exploration/Space_Science/BepiColombo/Win_a_trip_to_ESA_to_witness_BepiColombo_arrive_at_Mercury',
  'image_url': 'https://www.esa.int/var/esa/storage/images/esa_multimedia/images/2026/09/welcome_bepicolombo_to_mercury/27520540-1-eng-GB/Welcome_BepiColombo_to_Mercury_card_full.png',
  'news_site': 'ESA',
  'summary': 'Get ready to celebrate BepiColombo’s arrival at Mercury. Craft a welcoming message that could be a drawing, song, poem or any other art form and stand a chance to win a trip to mission control!\xa0',
  'published_at': '2026-09-24T13:00:00Z',
  'updated_at': '2026-09-24T13:40:23.146507Z',
  'featured': False,
  'launches': [],
  'events': []},
 {'id': 40073,
  'title': 'Record participation in ESA’s Industry Space Days 2026',
  'authors': [{'name': 'ESA', 'socials': None}],
  'url': 'https://www.esa.int/About_Us/Business_with_ESA/Record_participation_in_ESA_s_Industry_Space_Days_2026',
  'image_url': 'https://www.esa.int/var/esa/storage/images/esa_multimedia/images/2026/09/industry_space_days_20263/27536066-2-eng-GB/Industry_Space_Days_2026_card_full.jpg',
  'news_site': 'ESA',
  'summary': 'On 16–17 September, the European Space Agency (ESA) hosted a record 3100 visitors from Europe’s space industry for a two-day Industry Space Days (ISD) event at ESA’s ESTEC technical centre in the Netherlands.\xa0',
  'published_at': '2026-09-24T07:05:00Z',
  'updated_at': '2026-09-24T07:20:19.134672Z',
  'featured': False,
  'launches': [],
  'events': []},
 {'id': 40072,
  'title': 'ESA Awards RFA €2.7 Million in New Funding for SaxaVord Operations',
  'authors': [{'name': 'European Spaceflight', 'socials': None}],
  'url': 'https://europeanspaceflight.com/esa-awards-rfa-e2-7-million-in-new-funding-for-saxavord-operations/',
  'image_url': 'https://europeanspaceflight.com/wp-content/uploads/2026/09/ESA-Awards-RFA-2.7-Million-Euros-in-New-Funding-for-SaxaVord-Operations.webp',
  'news_site': 'European Spaceflight',
  'summary': 'The European Space Agency (ESA) has awarded Rocket Factory Augsburg (RFA) a contract amendment that will provide the company with €2.7 million in additional co-funding to support the build-out of the company’s launch and testing infrastructure at SaxaVord in Scotland. According to the agency, RFA is expected to resume preparations for static fire tests of […]\r\nThe post ESA Awards RFA €2.7 Million in New Funding for SaxaVord Operations appeared first on European Spaceflight.',
  'published_at': '2026-09-24T06:00:15Z',
  'updated_at': '2026-09-24T06:49:13.641073Z',
  'featured': False,
  'launches': [{'launch_id': '91b13c6c-4525-496d-997b-3521bb6a4cd8',
    'provider': 'Launch Library 2'}],
  'events': []},
 {'id': 40070,
  'title': 'APOD: 2026 September 24 – The Ghosts of Five Supernovas',
  'authors': [{'name': 'NASA', 'socials': None}],
  'url': 'https://science.nasa.gov/image-article/apod-2026-september-24-the-ghosts-of-five-supernovas/',
  'image_url': 'https://assets.science.nasa.gov/dynamicimage/assets/science/cds/apod/apod/2026/september/5SNR_Auriga_2000.jpg',
  'news_site': 'NASA',
  'summary': 'APOD Science APOD APOD: 2026 September 24 –… Today’s APOD Archive Submissions Index Search Calendar RSS Education About Discuss \xa0 APOD Astronomy Picture of the Day Discover the cosmos! Each day a different image or photograph of our fascinating universe is featured, along with a brief explanation written by a professional astronomer. OriginalAnnotated The Ghosts […]',
  'published_at': '2026-09-24T04:05:00Z',
  'updated_at': '2026-09-24T04:40:12.473370Z',
  'featured': False,
  'launches': [],
  'events': []},
 {'id': 40071,
  'title': 'Cloudy Cloak Over the Northwest',
  'authors': [{'name': 'NASA', 'socials': None}],
  'url': 'https://science.nasa.gov/earth/earth-observatory/cloudy-cloak-over-the-northwest/',
  'image_url': 'https://assets.science.nasa.gov/dynamicimage/assets/science/esd/eo/images/iotd/2026/cloudy-cloak-over-the-northwest/westcoastfog_tmo_20260919.jpg',
  'news_site': 'NASA',
  'summary': 'A low-lying cloud layer brought autumn ambience to western Washington and Oregon, while mountainous areas near the coast remained above the pall.',
  'published_at': '2026-09-24T04:01:00Z',
  'updated_at': '2026-09-24T04:50:13.492954Z',
  'featured': False,
  'launches': [],
  'events': []},
 {'id': 40069,
  'title': 'Swift Rescue Mission May Not Have Succeeded, But No Regrets',
  'authors': [{'name': 'Marcia Smith', 'socials': None}],
  'url': 'https://spacepolicyonline.com/news/swift-rescue-mission-may-not-have-succeeded-but-no-regrets/',
  'image_url': 'https://spacepolicyonline.com/wp-content/uploads/2026/07/Katalyst-LINK-Pegasus-300x203.jpg',
  'news_site': 'SpacePolicyOnline.com',
  'summary': 'The bold mission to extend the lifetime of NASA’s Swift observatory is coming to an end in the next 24 hours. Almost exactly one year after NASA signed a contract […]',
  'published_at': '2026-09-24T02:01:59Z',
  'updated_at': '2026-09-24T06:49:20.933302Z',
  'featured': False,
  'launches': [{'launch_id': 'db02116f-17ba-429a-b6c1-8e7f13b5e787',
    'provider': 'Launch Library 2'},
   {'launch_id': 'f596ad48-881e-47d6-806d-113c6dd97427',
    'provider': 'Launch Library 2'}],
  'events': []},
 {'id': 40068,
  'title': 'NASA Modernizes Commercial Airline Systems',
  'authors': [{'name': 'NASA', 'socials': None}],
  'url': 'https://www.nasa.gov/directorates/armd/aosp/nasa-modernizes-commercial-airline-systems/',
  'image_url': 'https://www.nasa.gov/wp-content/uploads/2026/09/acd26-0034-011.jpg',
  'news_site': 'NASA',
  'summary': 'NASA’s researchers know that when you settle into your seat on a commercial flight, you expect a smooth takeoff, views over the clouds, a steady descent, and hopefully an early arrival at your destination. But when your flight gets delayed on the tarmac instead of lifting off, or it ends up in a holding pattern […]',
  'published_at': '2026-09-23T22:08:54Z',
  'updated_at': '2026-09-23T22:10:18.229213Z',
  'featured': False,
  'launches': [],
  'events': []}]

In [ ]:
data_list = []

for item in articles:
    data_list.append({
        "title": item["title"],
        "news_site": item["news_site"],
        "published_at": item["published_at"],
        "url": item["url"],
        "summary": item["summary"]
    })

df = pd.DataFrame(data_list)
df

,title,news_site,published_at,url,summary
0,European Lunar Rover Secures Spot Aboard Blue ...,European Spaceflight,2026-09-24T13:45:53Z,https://europeanspaceflight.com/european-lunar...,Belgium’s Space Applications Services has secu...
1,Starfish Space’s first Otter servicing vehicle...,NASASpaceflight,2026-09-24T13:00:13Z,https://www.nasaspaceflight.com/2026/09/starfi...,Starfish Space has confirmed that its first fu...
2,New tests for rendezvous and docking interoper...,ESA,2026-09-24T13:00:00Z,https://www.esa.int/Enabling_Support/Space_Eng...,"Currently, space missions are one-shot affairs..."
3,Win a trip to ESA to witness BepiColombo arriv...,ESA,2026-09-24T13:00:00Z,https://www.esa.int/Science_Exploration/Space_...,Get ready to celebrate BepiColombo’s arrival a...
4,Record participation in ESA’s Industry Space D...,ESA,2026-09-24T07:05:00Z,https://www.esa.int/About_Us/Business_with_ESA...,"On 16–17 September, the European Space Agency ..."
5,ESA Awards RFA €2.7 Million in New Funding for...,European Spaceflight,2026-09-24T06:00:15Z,https://europeanspaceflight.com/esa-awards-rfa...,The European Space Agency (ESA) has awarded Ro...
6,APOD: 2026 September 24 – The Ghosts of Five S...,NASA,2026-09-24T04:05:00Z,https://science.nasa.gov/image-article/apod-20...,APOD Science APOD APOD: 2026 September 24 –… T...
7,Cloudy Cloak Over the Northwest,NASA,2026-09-24T04:01:00Z,https://science.nasa.gov/earth/earth-observato...,A low-lying cloud layer brought autumn ambienc...
8,"Swift Rescue Mission May Not Have Succeeded, B...",SpacePolicyOnline.com,2026-09-24T02:01:59Z,https://spacepolicyonline.com/news/swift-rescu...,The bold mission to extend the lifetime of NAS...
9,NASA Modernizes Commercial Airline Systems,NASA,2026-09-23T22:08:54Z,https://www.nasa.gov/directorates/armd/aosp/na...,NASA’s researchers know that when you settle i...